name: Swift 6 CBOR CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  # Build and test on multiple platforms
  build-and-test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["6.0.0"]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build -c release
    - name: Run tests with Swift Testing
      run: swift test

  # Generate documentation and deploy to GitHub Pages
  pages:
    name: Generate and Deploy Documentation
    needs: build-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    # Allow only one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0.0"
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Generate DocC Documentation
      run: |
        swift package --allow-writing-to-directory ./docs generate-documentation \
          --target CBOR \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path cbor \
          --output-path ./docs
    - name: Create GitHub Pages Artifact
      run: |
        # Create artifact directory
        mkdir -p _site
        # Copy documentation to artifact directory
        cp -R ./docs/* _site/
        # Create artifact
        cd _site
        tar -cf ../artifact.tar .
        cd ..
        # Upload artifact
        echo "GITHUB_PAGES_ARTIFACT_PATH=$(pwd)/artifact.tar" >> $GITHUB_ENV
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
      with:
        artifact_name: github-pages
        path: ${{ env.GITHUB_PAGES_ARTIFACT_PATH }}
